### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by vonavage** [openmainframeproject/ade#64]
how to use the rfc5434 parser in a standalone app? it fails with slf4j error or missing class

**Comment by caffreyj** [comment]
To document my private response.

Could you send me the java exception stack?  I suspect that the you need to
include some of the error logging code, the exception stack is likely to
confirm that.  One I understand the problem I can probably suggest a
solution

**Comment by vonavage** [comment]
@caffreyj 

I'm not sure how to invoke this... I tried as follows... using "**Test**" class in **org.openmainframe.ade.ext.os.parser** ... but, obviously will separate it out in package outside **org.openmainframe.ade.ext.os.parser** 
`package org.openmainframe.ade.ext.os.parser;
//import    org.openmainframe.ade.ext.os.parser.LinuxSyslog5424ParserBase;

public class Test
{
    public static void main(String args[])
    {
        LinuxSyslog5424ParserBase ls5424pb =  new LinuxSyslog5424ParserBase();

        String syslogWithNilPid = "<46>1 2014-05-30T08:52:40.620950-04:00 host-name rsyslogd - - - rsyslogd's groupid changed to 103";

        ls5424pb.parseLine(syslogWithNilPid);
    }
}
`

**java -cp ./ade-ext/target/ade-ext-1.0.4.jar    org.openmainframe.ade.ext.os.parser.Test**

`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.openmainframe.ade.ext.os.parser.LinuxSyslogLineParser.<clinit>(LinuxSyslogLineParser.java:45)
	at org.openmainframe.ade.ext.os.parser.Test.main(Test.java:8)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadCl`

**Comment by vonavage** [comment]
just to give the task that I'm trying is

- parse a syslog file  
- store the output to a file or write to stdout 
-- it can be a json  output or the object (which can be unpacked)

**Comment by caffreyj** [comment]
There are a set of jar files which the maven obtains when it builds an ADE image.  You will probably need to include those jar file in the class path for your parse code.  Here is a list of the jar which is used by ADE.
http://openmainframeproject.github.io/ade/open_source_used.html

**Comment by vonavage** [comment]
Thank you.. will use it
